# docker-compose.yaml
version: '3.8'

services:
  web:
    build: api/
    volumes:
      - ./api:/api
      - fastapi-data:/api/data
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  fastapi-data:
