name: Deploy FastAPI to Heroku

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Heroku CLI
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      run: |
        pip install -r requirements.txt
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Log in to Heroku
      run: heroku container:login

    - name: Push Docker Compose to Heroku
      run: heroku container:push web --app fast-api-project

    - name: Release Docker Compose on Heroku
      run: heroku container:release web --app fast-api-project
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
