name: Deploy FastAPI to Heroku

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version

    - name: Log in to Heroku Container Registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Push Docker Compose to Heroku
      run: heroku container:push web --app your-heroku-app-name

    - name: Release Docker Compose on Heroku
      run: heroku container:release web --app your-heroku-app-name
